events {}

http {
    upstream fraud_backend {
        server fraud:5000;
    }

    upstream churn_backend {
        server churn:5000;
    }
    upstream recommend_backend {
        server recommend:5000;
    }

    server {
        listen 80;

        location /fraud/ {
            proxy_pass http://fraud_backend/;
        }

        location /churn/ {
            proxy_pass http://churn_backend/;
        }
        location /recommend/ {
            proxy_pass http://recommend_backend/;
        }
    }
}

