services:
  model-api:
    build: ./app
    container_name: model-api
    ports:
      - "5000:5000"
    volumes:
      - ./model.pkl:/app/model.pkl:ro
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  redis:
    image: redis:7-alpine
    container_name: prod-redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: prod-nginx
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - model-api
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.13.0
    container_name: prod-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - model-api
    restart: unless-stopped

  grafana:
    image: grafana/grafana:13.1.0
    container_name: prod-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana2026
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    restart: unless-stopped

  traffic-generator:
    image: curlimages/curl:8.10.1
    container_name: prod-traffic
    depends_on:
      - nginx
    entrypoint:
      - /bin/sh
      - -c
      - |
        sleep 5
        while true; do
          curl -s -X POST -H 'Content-Type: application/json' \
            -d '{"amount":500,"hour":12,"num_tx_past_day":2}' \
            http://nginx:80/predict > /dev/null
          sleep 0.5
        done
    restart: unless-stopped