apiVersion: 1

contactPoints:
  - orgId: 1
    name: default
    receivers:
      - uid: default-email
        type: email
        settings:
          addresses: noreply@example.com
          singleEmail: false